VulnerabilityHistoryProject/chromium-vulnerabilities

cves/CVE-2011-3092.yml

Currently the commit points to nil. It needs to point to the note.

Fix nil reference

---

scripts/git_log_json.rb

Script generates JSON of the gitlog that is currently a .txt file. Run using -e (environment) -f (earliest commit) -l (latest commit) and -o (output dir).
ex: ruby git_log_json.rb -e ../ -f b5a47003e274f291f17146715cbb5b8c8fc2e441 -l da484cbe791ff85705210c5e065e865e9318aa98 -o ../commits/

Script to generate json

---

cves/CVE-2010-4490.yml
cves/CVE-2014-3198.yml

Completed CVE-2010-4490 and CVE-2014-3198

CVE-2010-4490 and CVE-2014-3198

---

cves/CVE-2015-1270.yml
cves/CVE-2015-1302.yml

submitting research on CVE-2015-1270 and CVE-2015-1302

CVE-2015-1302 and CVE-2015-1270

---

cves/CVE-2009-1413.yml
cves/CVE-2015-1284.yml

1 easy to understand less interesting vulnerability and 1 more complicated but more interesting vulnerability.

CVE-2009-1413 and CVE-2015-1284

---

cves/CVE-2010-1502.yml
cves/CVE-2015-1269.yml
cves/CVE-2015-6757.yml

CVE's all researched and updated

CVE-2010-1502 and CVE-2015-1269 and CVE-2015-6757

---

cves/CVE-2015-1271.yml
cves/CVE-2016-2844.yml

worked on CVE-2015-1271 and CVE-2016-2844

CVE-2015-1271 and CVE-2016-2844

---

cves/CVE-2011-3022.yml
cves/CVE-2015-1245.yml

CVE-2011-3022 and CVE-2015-1245

---

cves/CVE-2015-1209.yml
cves/CVE-2015-1282.yml

Please check CSVE-2015-1209. I could not find a hash because it was a much older commit. I included the revision number and the link to the SVN repository. I had to pad the revision number so the yaml checking script would stop yelling at me. This may break automation if they're looking specifically for a revision hash. This is what you told me to do in class though.

CSVE-2015-1209 and CSVE-2015-1282

---

cves/CVE-2014-1702.yml
cves/CVE-2014-7908.yml

CVE-2014-1702 and CVE-2014-7908

---

cves/CVE-2010-4494.yml
cves/CVE-2016-1639.yml

test to check if I can create a correct pull request

CVE 2016-1639 and CVE-2010-4494

---

cves/CVE-2013-6634.yml
cves/CVE-2016-1699.yml

Opening a PR for the sake of peer review
**These changes are NOT ready, please do not merge this yet.**

WIP CVE-2013-6634 and CVE-2016-1699

---

cves/CVE-2010-4035.yml
cves/CVE-2016-5142.yml

Worked on these CVES:
CVE-2010-4035
CVE-2016-5142

CVE-2010-4035 and CVE-2016-5142

---

cves/CVE-2013-6649.yml
cves/CVE-2015-1217.yml

Filled out details for the respective CVE yamls.

CVE-2013-6649 and CVE-2015-1217

---

cves/CVE-2010-3256.yml
cves/CVE-2015-1251.yml

Starting a pull request for CVE-2010-3256 and CVE-2015-1251 for Dan Fisher

CVE-2010-3256 and CVE-2015-1251

---

cves/CVE-2010-3247.yml
cves/CVE-2011-3960.yml

CVE-2010-3247 and CVE-2011-3960

---

cves/CVE-2016-1622.yml
cves/CVE-2016-1696.yml

Includes first commit that changes the description of CVE-2016-1622

CVE-2016-1622 and CVE-2016-1696

---

cves/CVE-2009-1441.yml
cves/CVE-2009-3263.yml
cves/CVE-2011-1120.yml

cve 2011 1120 and cve 2009 1441

---

cves/CVE-2012-5152.yml
cves/CVE-2015-8480.yml

CVE-2015-8480 and CVE-2012-5152

---

cves/CVE-2014-3172.yml
cves/CVE-2015-1236.yml

Modified CVE-2015-1236

---

cves/CVE-2013-0843.yml
cves/CVE-2015-6779.yml
cves/CVE-2016-5127.yml

CVE-2016-5127 CVE-2015-6779

---

cves/CVE-2013-6622.yml
cves/CVE-2016-1673.yml

CVE involves a use-after-free bug resulting from incorrect load delay timing of a media element. Elements were able to send a load event after being destroyed, creating the vulnerability.
CVE involves a browser-based XSS vulnerability resulting from lack of adherence to the Same Origin Policy. Requests were able to bypass checks determining whether request navigation should be allowed when they were sent into a frame in a new document.

CVE-2013-6622 and CVE-2016-1673

---

cves/CVE-2010-4202.yml
cves/CVE-2010-4576.yml
cves/CVE-2014-3803.yml

Completed research for CVE-2014-3803

CVE-2014-3803 and CVE-2010-4576

---

cves/CVE-2012-5149.yml
cves/CVE-2015-1276.yml

CVE-2012-5149

---

cves/CVE-2011-1112.yml
cves/CVE-2014-7941.yml

Researched CVE-2011-1112 and CVE-2014-7941

CVE-2011-1112 and CVE-2014-7941

---

cves/CVE-2010-1505.yml
cves/CVE-2011-2783.yml
cves/CVE-2013-6646.yml

Investigating vulnerabilities found in CVE-2011-2783 and CVE-2013-6646.

CVE-2011-2783 and CVE-2013-6646

---

cves/CVE-2011-3049.yml
cves/CVE-2015-1299.yml

CVE-2011-3049 and CVE-2015-1299 by Thomas Faticone in Predeep's section

CVE-2011-3049 and CVE-2015-1299

---

cves/CVE-2010-0656.yml
cves/CVE-2011-1811.yml
cves/CVE-2011-2836.yml

CVE-2011-1811
CVE-2011-2836
CVE-2010-0656
Ryan Hartzell

CVE-2011-1811, CVE-2011-2836, and CVE-2010-0656

---

cves/CVE-2010-3246.yml
cves/CVE-2013-6629.yml

Finished research for CVEs 2010-3246 and 2013-6629

Dxf7606 patch 1

---

cves/CVE-2014-3173.yml
cves/CVE-2015-1224.yml

CVE-2014-3173 and CVE-2015-1224

CVE-2014-3173 and CVE-2015-1224

---

cves/CVE-2010-2299.yml
cves/CVE-2016-1706.yml

Round 1 of history project for CVE-2010-2299 and CVE-2016-1706

CVE-2010-2299 and CVE-2016-1706

---

cves/CVE-2011-2358.yml
cves/CVE-2011-3876.yml

This is my round one investigation submission for the history project.

CVE-2011-2358 and CVE-2011-3876

---

cves/CVE-2013-2914.yml
cves/CVE-2015-6772.yml

CVE-2013-2914 and CVE-2015-6772 have been completed

CVE-2013-2914/CVE-2015-6772

---

.gitignore
cves/CVE-2012-4929.yml
cves/CVE-2014-1568.yml
cves/CVE-2015-3336.yml

Edit the CVE-2015-3336 file to include description and answers to various quetsions. Along with other small edits of files

CVE-2015-3336 and CVE-2014-1568

---

cves/CVE-2014-1719.yml
cves/CVE-2015-1279.yml

- Contains work for Round 1 of the History project

CVE-2014-1719.yml and CVE-2015-1279.yml

---

cves/CVE-2011-3061.yml
cves/CVE-2015-1227.yml

Contains reports for CVE-2011-3061 and CVE-2015-1227.

CVE-2011-3061 and CVE-2015-1227

---

cves/CVE-2010-4008.yml
cves/CVE-2014-1748.yml

Add curated cve's for Lucas Kretvix

CVE-2010-4008 and CVE-2014-1748

---

cves/CVE-2014-1723.yml
cves/CVE-2016-1660.yml

CVE-2014-1723 & CVE-2016-1660

---

cves/CVE-2010-0664.yml
cves/CVE-2011-3096.yml

Added in description for CVE-2010-0664 (stack exhaustion) and CVE-2011-3096 (use after free).

CVE-2010-0664 and CVE-2011-3096

---

cves/CVE-2011-2859.yml
cves/CVE-2016-1628.yml

CVE-2011-2859 CVE-2016-1628

---

cves/CVE-2010-3252.yml
cves/CVE-2011-3925.yml
cves/CVE-2014-1726.yml

Initial pull request. The yaml files, CVE-2010-3252 and CVE-2014-1726, were edited.

CVE-2010-3252 and CVE-2014-1726

---

cves/CVE-2013-6666.yml
cves/CVE-2016-1624.yml

Completed  vulnerabilities CVE-2013-6666 and CVE-2016-1624

CVE-2013-6666 and CVE-2016-1624

---

cves/CVE-2009-3934.yml
cves/CVE-2014-1700.yml

Completed the history of CVE-2014-1700 and CVE-2009-3934

CVE-2014-1700 and CVE-2009-3934

---

cves/CVE-2016-1679.yml
cves/CVE-2016-5130.yml

CVE-2016-5130 complete
CVE-2016-1679 complete

CVE-2016-5130 and CVE-2016-1679

---

cves/CVE-2011-2821.yml
cves/CVE-2015-1243.yml

Found a couple promising VCCS and some other info

Started CVE-2015

---

.gitignore
cves/CVE-2013-6653.yml
cves/CVE-2014-3196.yml
cves/CVE-2016-1711.yml

CVE-2013-6653.yml and CVE-2014-3196.yml have been set for curation. They will be completed later today.
CVE-2016-1711.yml will also be submitted later today - ignore commit 0af9e5b.

CVE-2013-6653, CVE-2014-3196, CVE-2016-1711

---

cves/CVE-2011-3953.yml
cves/CVE-2016-1697.yml

Curated CVE-2011-3953 and CVE-2016-1697 according to project round 1 instructions

CVE-2011-3953 and CVE-2016-1697

---

cves/CVE-2010-1503.yml
cves/CVE-2013-2845.yml

Round 1 submission for History Project

CVE-2010-1503 and CVE-2013-2845

---

cves/CVE-2014-3197.yml
cves/CVE-2016-1635.yml
cves/CVE-2016-5133.yml

Updated the information on CVE-2016-1635 and CVE-2016-5133

CVE-2016-1635 and CVE-2016-5133

---

cves/CVE-2011-3884.yml
cves/CVE-2014-1727.yml

CVE-2011-3884 and CVE-2014-1727
Zachary DiPasquale
RIT SWEN-331
ToDo:
Part 1 complete and passing:
Part 2 complete and passing:

CVE-2011-3884 AND CVE-2014-1727

---

cves/CVE-2011-2851.yml
cves/CVE-2014-1713.yml
cves/CVE-2015-1275.yml

CVE-2014-1713 & CVE-2011-2851

---

cves/CVE-2014-1715.yml
cves/CVE-2014-7939.yml

Round 1 and Round 2 of History Project.

CVE-2014-1715 and CVE-2014-7939

---

cves/CVE-2011-2849.yml
cves/CVE-2013-6663.yml

Initial commit of CVE-2013-6663 and CVE-2011-2849

CVE-2013-6663 and CVE-2011-2849

---

cves/CVE-2013-0891.yml
cves/CVE-2014-1732.yml

Initial pull request for setting up for future commits

CVE-2013-0891 and CVE-2014-1732

---

cves/CVE-2013-6656.yml
cves/CVE-2015-1216.yml
cves/CVE-2016-1641.yml

Currently just has initial commits for setting curated to true in the proper YML files.

CVE-2015-1216 and CVE-2016-1641

---

cves/CVE-2015-6775.yml
cves/CVE-2016-1619.yml

Updated CVE files for:
CVE-2016-1619 
CVE-2015-6755
Nathan Connor

CVE-2016-1619, CVE-2015-6755

---

cves/CVE-2011-2786.yml
cves/CVE-2015-6765.yml

CVE-2015-6765 and CVE-2011-2786

---

cves/CVE-2014-7946.yml
cves/CVE-2015-6583.yml

CVE-2014-7946 and CVE-2015-6583

---

cves/CVE-2010-4039.yml
cves/CVE-2014-1714.yml

CVE-2010-4039 and CVE-2014-1714

---

cves/CVE-2016-1647.yml
cves/CVE-2016-1671.yml

CVE-2016-1647 and CVE-2016-1671

---

cves/CVE-2011-2834.yml
cves/CVE-2013-6645.yml
cves/CVE-2014-9646.yml

CVE-2011-2834 and CVE-2014-9646

---

cves/CVE-2011-3965.yml
cves/CVE-2013-6655.yml
cves/CVE-2014-3156.yml

CVEs for history project SWEN-331

CVE-2014-3156 and CVE-2013-6655

---

cves/CVE-2013-6629.yml
cves/CVE-2013-6665.yml
spec/data/cve-skeleton.yml

A "nickname" is a plain-English title for a given vulnerability that would be shown alongside its CVE.

Add nicknames to CVE yml files

---

cves/CVE-2015-1210.yml
cves/CVE-2016-1700.yml

CVE-2016-1700 and CVE-2015-1210

---

cves/CVE-2011-3898.yml
cves/CVE-2015-1257.yml

Initial draft and PR of the YAML files for CVE-2011-3898 and CVE-2015-1257

CVE-2011-3898 and CVE-2015-1257

---

cves/CVE-2010-4488.yml
cves/CVE-2014-7937.yml

Initial committ of CVEs 2010-4488 & 2014-7937

Initial commit of CVEs 2010-4488 & 2014-7937

---

cves/CVE-2013-6635.yml
cves/CVE-2016-1661.yml
cves/CVE-2016-5140.yml

Initial commit
beginning swen 331 history project
set the curated flags to true in CVE-2016-1661 and CVE-2016-5140

CVE-2016-1661 & CVE-2013-6635

---

cves/CVE-2011-3083.yml

CVE-2011-3083

---

cves/CVE-2011-3964.yml
cves/CVE-2015-6774.yml

Updated the CVE-2015-6774 and CVE-2011-3964.

CVE-2015-6774 and CVE-2011-3964

---

cves/CVE-2015-6768.yml
cves/CVE-2016-5156.yml

Updated docs for SWEN-331 history assignment.

CVE-2015-6768 and CVE-2016-5156

---

cves/CVE-2011-1817.yml
cves/CVE-2011-2864.yml

Finished research on the two CVE: CVE-2011-1817 and CVE-2011-2864

CVE-2011-1817 and CVE-2011-2864

---

cves/CVE-2010-3118.yml
cves/CVE-2014-3154.yml

Curated documentation for CVEs: CVE-2014-3154 and CVE-2010-3118

CVE-2014-3154 and CVE-2010-3118

---

cves/CVE-2013-6658.yml
cves/CVE-2016-5174.yml

Completed both of CVE-2013-6658.yml and CVE-2016-5174.yml with manual curation

CVE-2013-6658 and CVE-2016-5174

---

cves/CVE-2014-1726.yml
cves/CVE-2014-7923.yml
spec/cve_spec.rb

Initial pull request of CVE-2014-1726 and CVE-2014-7923. Further comments needed pending nitron status.

CVE-2014-1726 and CVE-2014-7923

---

cves/CVE-2013-6643.yml
cves/CVE-2015-1272.yml

Filled out two CVEs. CVE-2013-6643 was Improper Authentication handling. CVE-2015-1272 was using memory after it was freed.

CVE-2013-6643 and CVE-2015-1272

---

cves/CVE-2011-1465.yml
cves/CVE-2014-3159.yml

Two CVE's updated. CVE-2014-3159 is related to potential for spoofing and CVE-2011-1465 is when an idle stream caused the system to crash.

CVE-2011-1465 and CVE-2014-3159

---

cves/CVE-2013-2858.yml
cves/CVE-2014-7935.yml

Added research for CVE-2014-7935 and CVE-2013-2858

CVE-2014-7935 and CVE-2013-2858

---

cves/CVE-2010-3117.yml
cves/CVE-2011-0776.yml

CVE-2010-3117 and CVE-2011-0776

---

cves/CVE-2010-4575.yml
cves/CVE-2012-5154.yml

Updated CVE-2010-4575.yml and CVE-2012-5154.yml files.

CVE-2010-4575 and CVE-2012-5154

---

cves/CVE-2011-1059.yml
cves/CVE-2011-2845.yml

Curated CVE-2011-1059 and CVE-2011-2845

CVE-2011-1059 and CVE-2011-2845

---

cves/CVE-2011-1434.yml
cves/CVE-2015-6769.yml

CVE 2011-1434 and CVE 2015-6769

---

cves/CVE-2009-1412.yml
cves/CVE-2014-1743.yml

Contribution for cves 2009-1412 and 2014-1743

CVE-2009-1412 and CVE-2014-1743

---

cves/CVE-2010-0644.yml
cves/CVE-2014-9689.yml

CVE-2010-0644 and CVE-2014-9689

---

cves/CVE-2013-2879.yml
cves/CVE-2016-1648.yml

jgk8960 History Project, studying CVE-2016-1648 and CVE-2013-2879. The .yml files related to these two vulnerabilities have been filled out through various research.

CVE-2016-1648 and CVE-2013-2879

---

cves/CVE-2011-3965.yml
cves/CVE-2016-1640.yml

This PR explores CVE-2016-1640, inline extension installation dialog bug, and CVE-2011-3965, a NULL pointer dereference problem in safe_browsing.

CVE-2016-1640 and CVE-2011-3965

---

cves/CVE-2015-1252.yml
cves/CVE-2015-1361.yml

Updated Research Docs to Include My Findings on the two CVEs

CVE-2015-1252, CVE-2015-1361

---

cves/CVE-2011-3094.yml
cves/CVE-2014-1701.yml

Listed in the title are the two (2) CVEs I've selected to investigate for this round, Round 1. Though I did run into some hiccups, I was successfully able to fill out all the answers to the following: CVE description, fix and vcc commits, whether the CVEs were unit tested or not, how the CVEs were initially discovered and when, what subsystems were the mistakes found in, if there were any interesting commits or major events occurring, if these vulnerabilities shared any common lessons from what we've learned so far in class, and what mistakes led to the vulnerabilities being introduced. The only thing left unanswered is the upvotes number, which is not required for Round 1.

Kimberly Sookoo -- CVE-2011-3094 and CVE-2014-1701

---

cves/CVE-2010-3413.yml
cves/CVE-2011-1443.yml
cves/CVE-2014-7924.yml

CVE-2010-3413 and CVE-2014-7924

---

cves/CVE-2015-1234.yml
cves/CVE-2016-5149.yml

Research, curate, and record findings on CVE-2015-1234 and CVE-2016-5149

CVE-2015-1234 and CVE-2016-5149

---

cves/CVE-2014-1745.yml
cves/CVE-2015-3334.yml

Researched and documented CVE-2014-1745 and CVE-2015-3334.

CVE-2014-1745 and CVE-2015-3334

---

cves/CVE-2011-1813.yml
cves/CVE-2016-1633.yml

Thank you @andymeneely for the feedback. I have made the changes you've recommended and have submitted a new pull request as a result.

CVE-2011-1813 and CVE-2016-1633

---

cves/CVE-2010-4484.yml
cves/CVE-2014-7948.yml

CVE-2010-4484 and CVE-2014-7948 

---

cves/CVE-2013-2839.yml
cves/CVE-2014-1733.yml

CVE-2014-1733 and CVE-2013-2839

CVE-2014-1733 and CVE-2013-2839

---

cves/CVE-2014-3161.yml
cves/CVE-2015-6766.yml

investigated and curated the yml files.

CVE-2015-6766 and CVE-2014-3161

---

cves/CVE-2015-6789.yml
cves/CVE-2016-1706.yml

Submitting research for CVEs 2015-6789 and 2016-1706.

CVE-2015-6789 and CVE-2016-1706

---

cves/CVE-2011-1439.yml
cves/CVE-2011-2837.yml

Committing my resarch for CVE-2012-1439 and CVE-2011-2837.

CVE-2011-1439 and CVE-2011-2837

---

cves/CVE-2014-7930.yml
cves/CVE-2016-5150.yml

Jack Corrigan History Project Part 1 pull request

CVE-2016-5150 and CVE-2014-7930

---

cves/CVE-2010-1231.yml
cves/CVE-2013-6656.yml

Curated research of CVE-2010-1231 and CVE-2013-6656.

CVE-2010-1231 and CVE-2013-6656

---

cves/CVE-2015-6780.yml

Submitting in two separate pull requests because YAML files are edited in GitHub. (I haven't yet figured out if I can edit multiple files and put them it one pull request all within GitHub)

CVE-2015-6780

---

cves/CVE-2014-3166.yml

Submitting in two separate pull requests because YAML files are edited in GitHub. (I haven't yet figured out if I can edit multiple files and put them it one pull request)

CVE-2014-3166

---

cves/CVE-2010-2108.yml
cves/CVE-2013-0841.yml

Filled out files regarding CVE-2010-2108 and CVE-2013-0841

CVE-2010-2108 and CVE-2013-0841

---

cves/CVE-2011-1435.yml
cves/CVE-2016-1623.yml

Modified the .yml files for CVE's 2011-1435 and 2016-1623.

CVE-2011-1435 and CVE-2016-1623

---

cves/CVE-2014-3189.yml
cves/CVE-2015-1255.yml

Adding further info to CVE-2014-3189: Out of bounds read and CVE-2015-1255: use-after-free

 CVE-2014-3189 and CVE-2015-1255

---

cves/CVE-2010-1505.yml
cves/CVE-2013-2873.yml
cves/CVE-2014-3191.yml
cves/CVE-2016-5163.yml

Completed analyses of these two CVEs for Round 1.

CVE-2010-1505 and CVE-2014-3191

---

cves/CVE-2013-6624.yml
cves/CVE-2016-1687.yml

CVE-2013-6624 - Use after free with ID attributes
CVE-2016-1687 - Non-private private classes

CVE-2013-6624 and CVE-2016-1687

---

cves/CVE-2016-1630.yml
cves/CVE-2016-1652.yml

CVE-2016-1630 - demonstrates a violation of the Same-Origin Policy, allowing attackers to access data in a resulting webpage without the proper origin.
CVE-2016-1652 - demonstrates a cross-site scripting vulnerability within the Extensions subsystem in Google Chrome

CVE-2016-1630 and CVE-2016-1652

---

cves/CVE-2015-1237.yml
cves/CVE-2015-6762.yml

This request curated the yml files of both CVE-2015-1237 and CVE-2015-6762.

CVE-2015-1237 and CVE-2015-6762

---

cves/CVE-2011-0485.yml
cves/CVE-2014-1747.yml

CVE-2014-1747 - UXSS from MHTML file
CVE-2011-0485 - Arbitrary code execution

CVE-2011-0485 and CVE-2014-1747

---

cves/CVE-2015-1240.yml
cves/CVE-2015-1288.yml
cves/CVE-2016-1686.yml

Investigation of two issues, the first one stemmed from an issue with an out-of-bounds error in the WebGL functions, and the second stemmed from an issue with an out-of-bounds error in the PDFium interpreter.

CVE-2015-1240 & CVE-2016-1686

---

cves/CVE-2013-0925.yml
cves/CVE-2016-1682.yml

Initial update of CVEs CVE-2016-1682 and CVE-2013-0925. CVE-2013-0925 is somewhat incomplete but is as filled out as I can get it at the moment.

CVE-2016-1682 and CVE-2013-0925

---

cves/CVE-2013-2844.yml
cves/CVE-2014-1744.yml

Integer Overflow and Use after free vulnerabilities

CVE-2014-1744 and CVE-2013-2844

---

cves/CVE-2010-1504.yml
cves/CVE-2011-1113.yml
cves/CVE-2013-0917.yml

Adding information for CVE 2011-1113 and CVE 2010-1504

CVE 2011-1113 and CVE 2010-1504

---

cves/CVE-2011-5319.yml
cves/CVE-2014-7941.yml

Creating a PR as per round 1 instruction 9 for CVE-2014-7941 and CVE-2011-5319.

CVE-2014-7941 and CVE-2011-5319

---

cves/CVE-2016-1645.yml

Add a nickname to address issue #585 [Study and nickname a vulnerability!].
Also added a commit message I was able to find.

Update CVE-2016-1645.yml - Add a nickname

---

cves/CVE-2010-1505.yml

adds nickname "Off to the Races"
play on words for the race condition getting beat during NTP

updates CVE-2010-1505 nickname

---

cves/CVE-2016-5157.yml

spelling/grammar fixes lines 36-47

---

cves/CVE-2010-0644.yml

Thought the play on "Sucks to be you" was appropriate for this vuln's nickname 😊

Nickname CVE-2010-0644 SOCKS To Be You

---

cves/CVE-2010-0656.yml
cves/CVE-2013-6657.yml

Finished CVE-2010-0656 and added curated to CVE-2013-6657, done

CVE-2010-0656 and CVE-2013-6657

---

cves/CVE-2010-4205.yml
cves/CVE-2013-2855.yml

Edited CVE-2010-4205 and CVE-2013-2855 for http://www.se.rit.edu/~swen-331/projects/history/

CVE-2010-4205 and CVE-2013-2855

---

cves/CVE-2017-5109.yml

CVE-2017-5109

---

cves/CVE-2011-0470.yml
cves/CVE-2015-6755.yml

consists of a notification handling bug and an open node vulnerability

CVE-2011-0470 and CVE-2015-6755

---

cves/CVE-2015-6779.yml
cves/CVE-2016-1689.yml

Contributing research information on two Chromium vulnerabilities.

CVE-2015-6779 and CVE-2016-1689

---

cves/CVE-2010-3415.yml
cves/CVE-2017-5038.yml

Adding information about two chromium vulnerabilities to the cve files.

cve-2010-3415 and cve-2017-5038

---

cves/CVE-2011-1108.yml
cves/CVE-2016-7549.yml

Adding information to the CVE files on two chromium vulnerabilities.

CVE-2016-7549 and CVE-2011-1108

---

cves/CVE-2011-1198.yml

Completed research and verified existing information.

CVE-2011-1198

---

cves/CVE-2011-2782.yml
cves/CVE-2016-5166.yml

CVE-2016-5166 and CVE-2011-2782

---

cves/CVE-2015-1281.yml

This file was mostly done before it was assigned to me but curated was not set to true.

CVE-2015-1281

---

cves/CVE-2011-2858.yml
cves/CVE-2015-1209.yml

Researching two vulnerabilities inside the chromium repo

CVE-2011-2858 and CVE-2015-1209

---

cves/CVE-2008-6998.yml

CVE-2008-6998 updated all the fields

CVE-2008-6998 updated all the fields

---

cves/CVE-2014-7908.yml
cves/CVE-2015-1292.yml

Investigations into two Chromium vulnerabilities.

CVE-2015-1292 and CVE-2014-7908

---

cves/CVE-2011-0784.yml

CVE-2011-0784

---

cves/CVE-2015-1282.yml

- Fixed syntax issues in YAML
- Set curated to true
- Added clarifying details
- Added missing details

CVE 2015-1282

---

cves/CVE-2015-1222.yml

CVE-2015-1222

---

cves/CVE-2017-5093.yml

Set curated to true, half done

CVE-2017-5093

---

cves/CVE-2016-5173.yml

Completed round 1 research on CVE-2016-5173

CVE-2016-5173

---

cves/CVE-2011-1413.yml

Update the YAML file for the assigned CVE and answered the questions within the file

CVE-2011-1413

---

cves/CVE-2016-5132.yml

CVE-2016-5132

---

cves/CVE-2011-0784.yml

Reverts VulnerabilityHistoryProject/chromium-vulnerabilities#290

Revert "CVE-2011-0784"

---

cves/CVE-2015-1241.yml

Reverts VulnerabilityHistoryProject/chromium-vulnerabilities#299

Revert "CVE-2015-1241"

---

cves/CVE-2011-0784.yml

Reverts VulnerabilityHistoryProject/chromium-vulnerabilities#317

Revert "Revert "CVE-2011-0784""

---

cves/CVE-2011-3045.yml
cves/CVE-2012-5108.yml
cves/CVE-2014-1723.yml
cves/CVE-2015-6781.yml
cves/CVE-2016-1707.yml

Added upvotes to the following vulnerabilities:
**CVE-2014-1723:** invisible right to left character that reverses characters after itself could load malicious JS - 9 upvotes
**CVE-2015-6781:** Integer overflow in font data could cause denial of service - 7 upvotes
**CVE-2011-3045:** Lack of controlled space for images can trigger integer overflow causing denial of service - 8 upvotes
**CVE-2016-1707:** On iPhone, users can spoof the address bar by using invalid inputs - 9 upvotes
**CVE-2012-5108:** Multi-threaded audio inputs caused race condition allowing arbitrary code execution through freed memory - 7 upvotes

Christopher's added upvotes

---

cves/CVE-2010-1505.yml
cves/CVE-2011-2850.yml
cves/CVE-2013-6657.yml
cves/CVE-2014-1748.yml
cves/CVE-2015-1296.yml

My contribution to leaning the app (Issue #759). I noticed a few small bugs. Firstly some 404 errors due to missing .yml files in the repo when trying to click on the upvote link. For example, this was the case for the vulnerability page for CVE-2011-3376. Another issue I ran into was when going back to the previous page I sometimes had to click the button in chrome multiple times. I can elaborate more on this in our meeting tomorrow.

Michael's Upvotes

---

cves/CVE-2009-1414.yml
cves/CVE-2010-3413.yml
cves/CVE-2014-1713.yml
cves/CVE-2014-3154.yml
cves/CVE-2016-5165.yml

just my upvotes and a typo fix!

Bryce upvotes

---

cves/CVE-2015-6768.yml

I would give this CVE 4 upvotes.

Elijah Upvotes CVE-2015-6768

---

cves/CVE-2016-5165.yml

I would give this CVE 8 upvotes.

Elijah Upvotes CVE-2016-5165

---

cves/CVE-2014-3154.yml

I would give this CVE 5 upvotes.

Elijah Upvotes CVE-2014-3154

---

cves/CVE-2014-7924.yml

I would give this CVE 4 upvotes.

Elijah upvotes CVE-2014-7924

---

cves/CVE-2014-1713.yml

I would give this CVE 7 upvotes.

Elijah upvotes CVE-2014-1713

---

cves/CVE-2014-1748.yml
cves/CVE-2015-1296.yml
cves/CVE-2015-6583.yml
cves/CVE-2016-1645.yml
cves/CVE-2016-5157.yml

Added upvotes to the following vulnerabilities:
**CVE-2014-1748**: The scrollbar rectangles for images were not properly being clipped to the the parent document that they interacted with (owning viewport). - 15 upvotes
**CVE-2015-6583**: Google Chrome’s browser does not display a location bar for hosted apps that navigate away from an installation site. - 19 upvotes
**CVE-2015-1296**: You could place special unicode characters in the URL so that a padlock character would be displayed at the beginning of the URL which could fool the user into thinking that they had a secure connection over HTTPS. - 30 upvotes
**CVE-2016-5157**: A Heap Buffer Overflow (out-of-bounds write) vulnerability was found in OpenJPEG, which is used in PDFium in Google Chrome. - 20 upvotes
**CVE-2016-1645**: …

Mjs6409 upvotes

---

cves/CVE-2014-7932.yml

Initially I committed the fix to the dev branch but I'll put it here as well. This was for issue 807

YML Parsing Issue for CVE-2014-7932
